# Generated by Django 2.2.3 on 2019-08-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponses',
            name='choice_corr',
        ),
        migrations.RemoveField(
            model_name='userresponses',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='question_attended',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserResponses',
        ),
    ]
