# Generated by Django 2.2.3 on 2019-08-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190816_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionForSetOneSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_for_sample_test', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Question Set One Sample',
            },
        ),
        migrations.CreateModel(
            name='ChoiceForSetOneSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1_A', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetOneSample')),
            ],
            options={
                'verbose_name': 'Choice Set One Sample',
            },
        ),
    ]
