# Generated by Django 2.2.3 on 2019-08-16 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_choiceforsetonereal_questionforsetonereal'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFeaturesSetOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Feature Question Set One',
            },
        ),
        migrations.CreateModel(
            name='QuestionFeaturesSetOneSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Feature Question Set One Sample',
            },
        ),
        migrations.AlterModelOptions(
            name='choiceforsetonereal',
            options={'verbose_name_plural': 'Choice Set One'},
        ),
        migrations.AlterModelOptions(
            name='choiceforsetonesample',
            options={'verbose_name_plural': 'Choice Set One Sample'},
        ),
        migrations.AlterModelOptions(
            name='questionforsetonereal',
            options={'verbose_name_plural': 'Question Set One'},
        ),
        migrations.AlterModelOptions(
            name='questionforsetonesample',
            options={'verbose_name_plural': 'Question Set One Sample'},
        ),
        migrations.CreateModel(
            name='UserResponsesForSetOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('choice_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetOneReal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses Set One',
            },
        ),
        migrations.CreateModel(
            name='UserResponsesForFeaturesSetOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='Feature_1')),
                ('choice_2', models.BooleanField(default=False, verbose_name='Feature_2')),
                ('choice_3', models.BooleanField(default=False, verbose_name='Feature_3')),
                ('choice_4', models.BooleanField(default=False, verbose_name='Feature_4')),
                ('choice_5', models.BooleanField(default=False, verbose_name='Feature_5')),
                ('choice_6', models.BooleanField(default=False, verbose_name='None of the above')),
                ('choice_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOne')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for features of Set One',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFeaturesSetOneSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOneSample')),
            ],
            options={
                'verbose_name_plural': 'Feature Choice Set One Sample',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFeaturesForSetOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOne')),
            ],
            options={
                'verbose_name_plural': 'Feature Choice Set One',
            },
        ),
    ]
