# Generated by Django 2.2.3 on 2019-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190816_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='question_attended_set_one_real',
            field=models.ManyToManyField(to='quiz.QuestionForSetOneReal'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='question_attended_set_one_sample',
            field=models.ManyToManyField(to='quiz.QuestionForSetOneSample'),
        ),
        migrations.AlterField(
            model_name='questionfeaturessetone',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionfeaturessetonesample',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionforsetonereal',
            name='question_text_for_real_test',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionforsetonesample',
            name='question_text_for_sample_test',
            field=models.CharField(max_length=200),
        ),
    ]
