# Generated by Django 2.2.3 on 2019-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190816_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponsesforfeaturessetone',
            name='choice_6',
            field=models.BooleanField(default=True, verbose_name='None of the above'),
        ),
    ]
