# Generated by Django 2.2.3 on 2019-08-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190817_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFeaturesSetTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Feature Questions for set 2',
            },
        ),
        migrations.CreateModel(
            name='QuestionFeaturesSetTwoSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sample Feature Questions for set 2',
            },
        ),
        migrations.CreateModel(
            name='QuestionForSetTwoReal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Questions for set 1',
            },
        ),
        migrations.CreateModel(
            name='QuestionForSetTwoSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_for_sample_test', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sample Questions for Set 2',
            },
        ),
        migrations.AlterModelOptions(
            name='choicefeaturesforsetone',
            options={'verbose_name_plural': 'Feature Choice Set 1'},
        ),
        migrations.AlterModelOptions(
            name='choiceforsetonereal',
            options={'verbose_name_plural': 'Choice Set 1'},
        ),
        migrations.AlterModelOptions(
            name='choiceforsetonesample',
            options={'verbose_name_plural': 'Choice Set 1 Sample'},
        ),
        migrations.AlterModelOptions(
            name='questionfeaturessetone',
            options={'verbose_name_plural': 'Feature Question Set 1'},
        ),
        migrations.AlterModelOptions(
            name='questionforsetonereal',
            options={'verbose_name_plural': 'Question Set 1'},
        ),
        migrations.AlterModelOptions(
            name='questionforsetonesample',
            options={'verbose_name_plural': 'Question Set 1 Sample'},
        ),
        migrations.CreateModel(
            name='UserResponsesForSetTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='sample1_A')),
                ('choice_2', models.BooleanField(default=False, verbose_name='sample2_A')),
                ('choice_3', models.BooleanField(default=False, verbose_name='sample3_A')),
                ('choice_4', models.BooleanField(default=False, verbose_name='sample4_A')),
                ('choice_5', models.BooleanField(default=False, verbose_name='sample5_A')),
                ('choice_6', models.BooleanField(default=False, verbose_name='sample6_A')),
                ('choice_7', models.BooleanField(default=False, verbose_name='sample7_A')),
                ('choice_8', models.BooleanField(default=False, verbose_name='sample8_A')),
                ('choice_9', models.BooleanField(default=False, verbose_name='sample9_A')),
                ('choice_10', models.BooleanField(default=False, verbose_name='sample10_A')),
                ('choice_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoReal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses Set 2',
            },
        ),
        migrations.CreateModel(
            name='UserResponsesForFeaturesSetTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1', models.BooleanField(default=False, verbose_name='Feature_1')),
                ('choice_2', models.BooleanField(default=False, verbose_name='Feature_2')),
                ('choice_3', models.BooleanField(default=False, verbose_name='Feature_3')),
                ('choice_4', models.BooleanField(default=False, verbose_name='Feature_4')),
                ('choice_5', models.BooleanField(default=False, verbose_name='Feature_5')),
                ('choice_6', models.BooleanField(default=False, verbose_name='None of the above')),
                ('choice_corr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails')),
            ],
            options={
                'verbose_name_plural': 'User Responses for features of Set 2',
            },
        ),
        migrations.CreateModel(
            name='ChoiceForSetTwoSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1_A', models.ImageField(upload_to='images/')),
                ('sample2_A', models.ImageField(upload_to='images/')),
                ('sample3_A', models.ImageField(upload_to='images/')),
                ('sample4_A', models.ImageField(upload_to='images/')),
                ('sample5_A', models.ImageField(upload_to='images/')),
                ('sample6_A', models.ImageField(upload_to='images/')),
                ('sample7_A', models.ImageField(upload_to='images/')),
                ('sample8_A', models.ImageField(upload_to='images/')),
                ('sample9_A', models.ImageField(upload_to='images/')),
                ('sample10_A', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoSample')),
            ],
            options={
                'verbose_name_plural': 'Sample Choice for set 2',
            },
        ),
        migrations.CreateModel(
            name='ChoiceForSetTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1_A', models.ImageField(upload_to='images/')),
                ('sample2_A', models.ImageField(upload_to='images/')),
                ('sample3_A', models.ImageField(upload_to='images/')),
                ('sample4_A', models.ImageField(upload_to='images/')),
                ('sample5_A', models.ImageField(upload_to='images/')),
                ('sample6_A', models.ImageField(upload_to='images/')),
                ('sample7_A', models.ImageField(upload_to='images/')),
                ('sample8_A', models.ImageField(upload_to='images/')),
                ('sample9_A', models.ImageField(upload_to='images/')),
                ('sample10_A', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoReal')),
            ],
            options={
                'verbose_name_plural': 'Choice for set 2',
            },
        ),
        migrations.CreateModel(
            name='ChoiceFeaturesForSetTwoSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwoSample')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceFeaturesForSetTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1_A', models.ImageField(upload_to='images/')),
                ('feature2_A', models.ImageField(upload_to='images/')),
                ('feature1_B', models.ImageField(upload_to='images/')),
                ('feature2_B', models.ImageField(upload_to='images/')),
                ('feature1_C', models.ImageField(upload_to='images/')),
                ('feature2_C', models.ImageField(upload_to='images/')),
                ('feature1_D', models.ImageField(upload_to='images/')),
                ('feature2_D', models.ImageField(upload_to='images/')),
                ('feature1_E', models.ImageField(upload_to='images/')),
                ('feature2_E', models.ImageField(upload_to='images/')),
                ('question_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwo')),
            ],
            options={
                'verbose_name_plural': 'Feature Choice for set 2',
            },
        ),
    ]
