# Generated by Django 2.2.3 on 2019-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20190817_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='question_attended_set_two_real',
            field=models.ManyToManyField(to='quiz.QuestionForSetTwoReal'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='question_attended_set_two_sample',
            field=models.ManyToManyField(to='quiz.QuestionForSetTwoSample'),
        ),
    ]
