# Generated by Django 2.2.3 on 2019-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190817_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicefeaturesforsettwosample',
            options={'verbose_name_plural': 'Feature Choice for Set 2 Sample'},
        ),
        migrations.AlterModelOptions(
            name='choicefeaturessetonesample',
            options={'verbose_name_plural': 'Feature Choice Set 1 Sample'},
        ),
        migrations.AlterModelOptions(
            name='questionfeaturessetonesample',
            options={'verbose_name_plural': 'Feature Question Set 1 Sample'},
        ),
        migrations.AlterModelOptions(
            name='questionforsettworeal',
            options={'verbose_name_plural': 'Questions for set 2'},
        ),
        migrations.AlterModelOptions(
            name='userresponsesforfeaturessetone',
            options={'verbose_name_plural': 'User Responses for features of Set 1'},
        ),
        migrations.AlterModelOptions(
            name='userresponsesforsetone',
            options={'verbose_name_plural': 'User Responses Set 1'},
        ),
        migrations.AddField(
            model_name='questionforsettworeal',
            name='question_text_for_real_test',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='questionforsettwosample',
            name='question_text_for_sample_test',
            field=models.CharField(max_length=200),
        ),
    ]
