# Generated by Django 2.2.3 on 2019-09-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190817_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponsesforfeaturessetone',
            name='choice_6',
        ),
        migrations.RemoveField(
            model_name='userresponsesforfeaturessettwo',
            name='choice_6',
        ),
        migrations.AlterField(
            model_name='choicefeaturesforsetone',
            name='question_rel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOne'),
        ),
        migrations.AlterField(
            model_name='choicefeaturesforsettwo',
            name='question_rel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwo'),
        ),
        migrations.AlterField(
            model_name='choicefeaturesforsettwosample',
            name='question_rel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwoSample'),
        ),
        migrations.AlterField(
            model_name='choicefeaturessetonesample',
            name='question_rel',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOneSample'),
        ),
        migrations.AlterField(
            model_name='choiceforsetonereal',
            name='question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetOneReal'),
        ),
        migrations.AlterField(
            model_name='choiceforsetonesample',
            name='question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetOneSample'),
        ),
        migrations.AlterField(
            model_name='choiceforsettwo',
            name='question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoReal'),
        ),
        migrations.AlterField(
            model_name='choiceforsettwosample',
            name='question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoSample'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeaturessetone',
            name='choice_corr',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetOne'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeaturessetone',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeaturessettwo',
            name='choice_corr',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionFeaturesSetTwo'),
        ),
        migrations.AlterField(
            model_name='userresponsesforfeaturessettwo',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.UserDetails'),
        ),
        migrations.AlterField(
            model_name='userresponsesforsetone',
            name='choice_corr',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetOneReal'),
        ),
        migrations.AlterField(
            model_name='userresponsesforsettwo',
            name='choice_corr',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionForSetTwoReal'),
        ),
    ]
