# Generated by Django 2.2.6 on 2019-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Choices'},
        ),
        migrations.RemoveField(
            model_name='stimuli',
            name='stimuli',
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_1',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_10',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_2',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_3',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_4',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_5',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_6',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_7',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_8',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stimuli',
            name='stimuli_9',
            field=models.ImageField(default='Contrast00.png', upload_to='images/'),
        ),
    ]
