# Generated by Django 2.2.6 on 2019-10-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllTogether', '0002_auto_20191013_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='stimuli_attended',
        ),
    ]
